### ISSUE TITLE
how do i login???

### ISSUE THREAD

**Issue by JustJasonLol** [GamerPablito/GameJolt-Adaptation-for-FNF-and-Haxeflixel#4]
im killing my brain i tried everything and i cant login

**Comment by GamerPablito** [comment]
You have to set your own info in the `setUserInfo()` and then use `login()`

**Comment by JustJasonLol** [comment]
thx bro, it works

**Comment by GamerPablito** [comment]
@JustJasonLol  Nice, glad this was helpful for ya :)
