### ISSUE TITLE
Hey i am really dumb 

### ISSUE THREAD

**Issue by machonessiebaby** [GamerPablito/GameJolt-Adaptation-for-FNF-and-Haxeflixel#7]
so i know the import goes at the top but what i dont understand is why the part below gives me errors
![image](https://user-images.githubusercontent.com/56323671/202860289-84c07441-8248-4562-b57d-570567132ec7.png)
or what hx file would it go in

sorry if this is a simple answer like i said i am very dumb

```
#if GAMEJOLT_ALLOWED
import gamejolt.GJClient;
#end
  //this line below is giving me errors
class Example extends FlxUIState
{
  override function create()
  {
    super.create();

    #if GAMEJOLT_ALLOWED
    GJClient.initialize();
    #end
  }
}```

**Comment by GamerPablito** [comment]
First, the Example script you send me above is not initialized in the first 2 lines (has an `#end` but not a `#if GAMEJOLT_ALLOWED`)
Second, I made that script in order to let users know how to put the XML tags in the coding, you don't have to create more hx files (only the one for the GameJolt Menu as you prefer).

**Comment by machonessiebaby** [comment]
> First, the Example script you send me above is not initialized in the first 2 lines (has an `#end` but not a `#if GAMEJOLT_ALLOWED`) Second, I made that script in order to let users know how to put the XML tags in the coding, you don't have to create more hx files (only the one for the GameJolt Menu as you prefer).

ah ok ill fix that

**Comment by machonessiebaby** [comment]
![image](https://user-images.githubusercontent.com/56323671/202865182-a93ec072-f7e2-4a52-8811-10e520fa21da.png)
![image](https://user-images.githubusercontent.com/56323671/202865187-643f0ac9-897f-4718-b8a1-917cf4900cb3.png)

**Comment by machonessiebaby** [comment]
I moved the code and now its saying this 
![image](https://user-images.githubusercontent.com/56323671/202865231-3d76ff39-8843-4e80-ab9b-0819a4b3fe64.png)

**Comment by machonessiebaby** [comment]
okay the error has changed i added the `<define name="GAMEJOLT_ALLOWED" if="desktop" unless="ACHIEVEMENTS_ALLOWED">`

now it says
![image](https://user-images.githubusercontent.com/56323671/202865494-ed5363e8-e8c0-4cfc-ba75-98ff3506c1f6.png)

**Comment by machonessiebaby** [comment]
yeah so 
`<define name="GAMEJOLT_ALLOWED" if="desktop" unless="ACHIEVEMENTS_ALLOWED">` is causing the error?

**Comment by GamerPablito** [comment]
You don't have to use the `-debug` command, only `lime test windows`

**Comment by GamerPablito** [comment]
Or maybe there's another line that's not formatted or typed correctly

**Comment by machonessiebaby** [comment]
> You don't have to use the `-debug` command, only `lime test windows`

im jsut using the -debug for testing ill check the regular build

**Comment by machonessiebaby** [comment]
> Or maybe there's another line that's not formatted or typed correctly

![image](https://user-images.githubusercontent.com/56323671/202865645-5b1d42d6-ad1b-4573-abf2-31754ff6d339.png)

**Comment by GamerPablito** [comment]
Guess I see the problem

**Comment by machonessiebaby** [comment]
> Guess I see the problem

location??

**Comment by GamerPablito** [comment]
The lines are all closed by `<>` right?
But the line where the GameJolt line is, it doesn't contain the slash `/` at the end, like the others

**Comment by machonessiebaby** [comment]
> The lines are all closed by `<>` right? But the line where the GameJolt line is, it doesn't contain the slash `/` at the end, like the others

ohhhh sorry

**Comment by machonessiebaby** [comment]
alright thanks

**Comment by GamerPablito** [comment]
No, don't worry, was my fault to don't include that before, so:
Instead of: `<define name="GAMEJOLT_ALLOWED" if="desktop" unless="ACHIEVEMENTS_ALLOWED">`
You have to type `<define name="GAMEJOLT_ALLOWED" if="desktop" unless="ACHIEVEMENTS_ALLOWED" />`

**Comment by GamerPablito** [comment]
> alright thanks

Anytime ;)
