### ISSUE TITLE
Hey i think this should be checked

### ISSUE THREAD

**Issue by machonessiebaby** [GamerPablito/GameJolt-Adaptation-for-FNF-and-Haxeflixel#8]
![image](https://user-images.githubusercontent.com/56323671/202876030-cfee6c47-36f2-4bdc-a8f9-561cd5c51dac.png)
i think this might need to be adressed

**Comment by machonessiebaby** [comment]
yeah i forgot a folder

**Comment by GamerPablito** [comment]
Oh ok, there's no problem then
