### ISSUE TITLE
Am I suppsed to make a new state so people can login?

### ISSUE THREAD

**Issue by IdiotLimitedEdition** [GamerPablito/GameJolt-Adaptation-for-FNF-and-Haxeflixel#9]

**Comment by GamerPablito** [comment]
Of course, this client only contains tools and commands, not menus.
But I think you know how to make that with no problem, am I wrong?

**Comment by machonessiebaby** [comment]
> Of course, this client only contains tools and commands, not menus. But I think you know how to make that with no problem, am I wrong?

well shit looks like im screwed ;-;

**Comment by GamerPablito** [comment]
@machonessiebaby if you want, I have some template menus to make it work, I can send them to you so you can find a way to implement it in your mod/game

**Comment by Eventretta** [comment]
> Of course, this client only contains tools and commands, not menus. But I think you know how to make that with no problem, am I wrong?

gamerpablito indirectly roasting lol
